### ISSUE TITLE
RangeError: toString() radix argument must be between 2 and 36

### ISSUE THREAD

**Issue by KristerV** [lfergon/meteor-export-csv#3]
not sure what to do with this.

**Error**

```
Exception while invoking method 'exportCSV' RangeError: toString() radix argument must be between 2 and 36
    at Number.toString (native)
    at [object Object].ExportCSV.exportToCSV (packages/lfergon:exportcsv/lib/exportcsv.js:32:1)
    at [object Object].Meteor.methods.exportCSV (app/server/exportCSV.js:3:20)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
    at packages/ddp/livedata_server.js:648:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp/livedata_server.js:647:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
    at packages/ddp/livedata_server.js:546:1
```

**Client**

```
'click button.export-csv': function(e) {
    Meteor.call('exportCSV', function(err, fileContent) {
        if (err)
            sAlert.error("Error: " + err)

        if(fileContent){
            var blob = new Blob([fileContent], {type: "text/plain;charset=utf-8"});
            saveAs(blob, nameFile);
        }
    });
}
```

**Server**

```
Meteor.methods({
    exportCSV: function() {
        return exportcsv.exportToCSV(ProductsCollection.find().fetch());
    }
})
```

**Comment by KristerV** [comment]
http://stackoverflow.com/questions/16527109/javascript-date-tostring-radix-argument-error

seems to suggest it's caused by Date. Which I do have. Namely I've got date objects saved as pure `new Date()` values. And I think some of the values are coming from Autoform.

**Comment by KristerV** [comment]
okay I cloned this repo and traced it down. It's not the Date, its the Number. I can actually reproduce this in both server and browser:

![screenshot_2015-06-22_13-42-56](https://cloud.githubusercontent.com/assets/2750622/8280302/b7b3bb54-18e4-11e5-9a13-3141fa4dc316.png)

Works fine without "utf8".
